"""Ingestion data models representing intermediate page extraction and chunks."""
from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class DocumentPage:
    """Normalized representation of a single extracted document page."""
    page_number: int  # 1-indexed page number
    text: str
    source_type: str  # e.g., 'pdf', 'docx', 'txt', 'image'
    used_ocr: bool = False


@dataclass(frozen=True)
class ProcessedChunk:
    """Normalized chunk generated by structure-aware chunker."""
    chunk_index: int  # 0-indexed sequential order
    content: str
    page_number_start: int
    page_number_end: int
    token_count: int
